export const GET_POSTS_START   = "GET_POSTS_START"
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS"
export const GET_POSTS_FAILURE = "GET_POSTS_FAILURE"

export const GET_POST_START   = "GET_POST_START"
export const GET_POST_SUCCESS = "GET_POST_SUCCESS"
export const GET_POST_FAILURE = "GET_POST_FAILURE"

export const ADD_POST_START   = "ADD_POST_START"
export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS"
export const ADD_POST_FAILURE = "ADD_POST_FAILURE"

export const EDIT_POST_START   = "EDIT_POST_START"
export const EDIT_POST_SUCCESS = "EDIT_POST_SUCCESS"
export const EDIT_POST_FAILURE = "EDIT_POST_FAILURE"

export const DELETE_POST_START   = "DELETE_POST_START"
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS"
export const DELETE_POST_FAILURE = "DELETE_POST_FAILURE"
